# Generated by Django 4.2 on 2024-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_capacity', models.PositiveIntegerField(verbose_name='Встановлена потужність')),
            ],
        ),
    ]
