# Generated by Django 4.2 on 2024-04-14 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tps_alter_station_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Назва'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='normal_mode',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Відсоток потужності в штатному режимі'),
            preserve_default=False,
        ),
    ]
