# Generated by Django 4.2 on 2024-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_station_name_station_normal_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='installed_capacity',
        ),
        migrations.RemoveField(
            model_name='station',
            name='normal_mode',
        ),
        migrations.AddField(
            model_name='station',
            name='block_count',
            field=models.IntegerField(default=1, verbose_name='Кількість енергоблоків'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='current_power',
            field=models.FloatField(default=1, verbose_name='Поточна потужність (МВт)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Розташування'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='max_power',
            field=models.FloatField(default=1, verbose_name='Максимальна потужність (МВт)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
