# Generated by Django 4.2 on 2024-05-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_station_installed_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='Довгота'),
            preserve_default=False,
        ),
    ]
