# Generated by Django 4.2 on 2024-05-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_station_location_station_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='standart_power',
            field=models.FloatField(default=0, verbose_name='Стандартна потужність (МВт)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='current_power',
            field=models.FloatField(verbose_name='Поточна потужність (МВт)'),
        ),
    ]
